# Welcome to Jekyll!
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alex le mi-grand
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexlemigrand.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alexlemigrand
github_username:  jekyll

# Author settings
author: Alex le mi-grand
author-pic: alm.png
about-author: Bonjour, je m'appelle Alexandre. Après deux premiers voyages touristiques au Japon, j'ai sauté le pas pour un voyage plus long avec un visa vacances travail (2015-2016). J'y fait depuis d'autres voyages touristiques ! A l'occasion du PVT, j'ai commencé ce blog afin que ma famille et mes amis puissent me suivre plus facilement, et toutes les personnes qui se seraient perdues ou à la recherche de contenu sur le Japon. Je partage -sporadiquement-, avec vous, mes expériences et ce que j'aime sur ce beau pays qu'est le Japon ! J'espère que la lecture sera aussi plaisante que les moments que je vis !

website: alexlemigrand.net
twitter: alexlemigrand
github: alexkoudingu/blog-alm

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
#theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

#serveri
host: 0.0.0.0
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
